[package]
name = "alphagozero_rs"
version = "0.1.0"
authors = ["s-en <sen@nemusoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true

[dependencies]
auto_ops = "0.3.0"